import nodemailer from "nodemailer";
import type { CliSignals, ScanConfig, ScoringResult } from "./types";

// ── Email ─────────────────────────────────────────────────────────────────────

function buildEmailBody(signals: CliSignals, scoring: ScoringResult): string {
  const verdictEmoji = scoring.verdict === "healthy" ? "✅" : scoring.verdict === "needs_attention" ? "⚠️" : "🔴";
  const dim = scoring.scores;

  return `
<div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 600px; margin: 0 auto; background: #f8fafc; padding: 0;">
  <!-- Header -->
  <div style="background: #2D4EFF; color: white; padding: 32px 32px 24px; border-radius: 8px 8px 0 0;">
    <h1 style="margin: 0; font-size: 22px; font-weight: 700;">Project Health Report</h1>
    <p style="margin: 6px 0 0; opacity: 0.85; font-size: 14px;">${signals.project_name}</p>
    <p style="margin: 4px 0 0; opacity: 0.7; font-size: 12px;">${new Date(signals.scanned_at).toLocaleString()}</p>
  </div>

  <!-- Score band -->
  <div style="background: ${scoring.health_score >= 70 ? "#16A34A" : scoring.health_score >= 45 ? "#D97706" : "#DC2626"}; color: white; padding: 16px 32px; display: flex; align-items: center; gap: 16px;">
    <span style="font-size: 36px; font-weight: 900; line-height: 1;">${scoring.grade}</span>
    <div>
      <div style="font-size: 20px; font-weight: 700;">${scoring.health_score}/100</div>
      <div style="font-size: 13px; opacity: 0.9;">${verdictEmoji} ${capitalize(scoring.verdict.replace("_", " "))}</div>
    </div>
  </div>

  <!-- Scores -->
  <div style="background: white; padding: 24px 32px; border-left: 1px solid #e2e8f0; border-right: 1px solid #e2e8f0;">
    <h2 style="font-size: 14px; color: #64748b; text-transform: uppercase; letter-spacing: 0.05em; margin: 0 0 16px;">Dimension Scores</h2>
    ${renderScoreRow("Code Quality", dim.code_quality.score)}
    ${renderScoreRow("Security", dim.security.score)}
    ${renderScoreRow("Performance", dim.performance.score)}
    ${renderScoreRow("Test Coverage", dim.test_coverage.score)}
    ${renderScoreRow("Readability", dim.readability.score)}
  </div>

  <!-- Critical issues -->
  ${buildCriticalSection(signals)}

  <!-- Footer -->
  <div style="background: #f1f5f9; padding: 16px 32px; border-radius: 0 0 8px 8px; border: 1px solid #e2e8f0; border-top: none;">
    <p style="margin: 0; color: #94a3b8; font-size: 11px; text-align: center;">
      Generated by <strong>@webileapps/scan</strong> — full details in the attached PDF
    </p>
  </div>
</div>`.trim();
}

function renderScoreRow(label: string, score: number): string {
  const color = score >= 7.5 ? "#16A34A" : score >= 5.5 ? "#D97706" : "#DC2626";
  const pct = Math.round((score / 10) * 100);
  return `
  <div style="margin-bottom: 12px;">
    <div style="display: flex; justify-content: space-between; margin-bottom: 4px;">
      <span style="font-size: 13px; color: #1e293b;">${label}</span>
      <span style="font-size: 13px; font-weight: 700; color: ${color};">${score.toFixed(1)}</span>
    </div>
    <div style="background: #e2e8f0; border-radius: 9999px; height: 6px;">
      <div style="background: ${color}; width: ${pct}%; height: 6px; border-radius: 9999px;"></div>
    </div>
  </div>`;
}

function buildCriticalSection(signals: CliSignals): string {
  const items: string[] = [];

  if (signals.has_secret_files.length > 0) {
    items.push(`🔴 <strong>Secret files in repository:</strong> ${signals.has_secret_files.slice(0, 3).join(", ")}`);
  }
  if ((signals.content?.secret_hits.length ?? 0) > 0) {
    items.push(`🔴 <strong>${signals.content?.secret_hits.length} hardcoded credential(s)</strong> detected in source code`);
  }
  if ((signals.deps?.vulnerable.length ?? 0) > 0) {
    items.push(`⚠️ <strong>${signals.deps?.vulnerable.length} vulnerable dependency/ies:</strong> ${signals.deps?.vulnerable.map((v) => v.name).slice(0, 3).join(", ")}`);
  }
  if (signals.test_files === 0) {
    items.push("⚠️ <strong>No tests detected</strong> — the project has no automated safety net");
  }
  if (!signals.has_ci_gitlab && !signals.has_ci_github) {
    items.push("⚠️ <strong>No CI/CD pipeline</strong> configured");
  }

  if (items.length === 0) return "";

  return `
  <div style="background: #FEF2F2; border-left: 4px solid #DC2626; padding: 16px 20px; margin: 0 32px 0; border-radius: 0 4px 4px 0;">
    <h3 style="font-size: 13px; color: #991B1B; margin: 0 0 10px; text-transform: uppercase; letter-spacing: 0.05em;">Action Required</h3>
    ${items.map((i) => `<p style="margin: 0 0 8px; font-size: 13px; color: #7F1D1D;">${i}</p>`).join("")}
  </div>`;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

export async function sendEmail(
  pdfBuffer: Buffer,
  signals: CliSignals,
  scoring: ScoringResult,
  recipients: string[],
  config: ScanConfig
): Promise<void> {
  const emailCfg = config.notify?.email;
  if (!emailCfg) {
    process.stderr.write("[scan] No email config — skipping email notification\n");
    return;
  }
  if (recipients.length === 0) {
    process.stderr.write("[scan] No recipients — skipping email notification\n");
    return;
  }

  let transporter: nodemailer.Transporter;

  if (emailCfg.smtp?.host) {
    transporter = nodemailer.createTransport({
      host: emailCfg.smtp.host,
      port: emailCfg.smtp.port ?? 587,
      secure: emailCfg.smtp.secure ?? (emailCfg.smtp.port === 465),
      auth: {
        user: emailCfg.smtp.user,
        pass: emailCfg.smtp.pass,
      },
    });
  } else if (emailCfg.resend?.apiKey) {
    // Resend supports standard SMTP at smtp.resend.com:465
    transporter = nodemailer.createTransport({
      host: "smtp.resend.com",
      port: 465,
      secure: true,
      auth: { user: "resend", pass: emailCfg.resend.apiKey },
    });
  } else {
    process.stderr.write("[scan] Email config present but no SMTP or Resend credentials — skipping\n");
    return;
  }

  const dateStr = new Date(signals.scanned_at).toISOString().slice(0, 10);
  const gradeEmoji = scoring.grade === "A" ? "✅" : scoring.grade === "B" ? "🟢" : scoring.grade === "C" ? "🟡" : "🔴";
  const subject = `${gradeEmoji} ${signals.project_name} Health Report — ${scoring.grade} (${scoring.health_score}/100) — ${dateStr}`;

  try {
    await transporter.sendMail({
      from: emailCfg.from,
      to: recipients.join(", "),
      subject,
      html: buildEmailBody(signals, scoring),
      attachments: [
        {
          filename: `health-report-${signals.project_name.replace(/[^a-z0-9]/gi, "-").toLowerCase()}-${dateStr}.pdf`,
          content: pdfBuffer,
          contentType: "application/pdf",
        },
      ],
    });
    process.stdout.write(`[scan] Email sent to ${recipients.length} recipient(s)\n`);
  } catch (e) {
    process.stderr.write(`[scan] Email send failed: ${(e as Error).message}\n`);
  }
}

// ── Google Chat ────────────────────────────────────────────────────────────────

function ciArtifactUrl(): string | null {
  const projectUrl = process.env.CI_PROJECT_URL;
  const jobId = process.env.CI_JOB_ID;
  if (!projectUrl || !jobId) return null;
  return `${projectUrl}/-/jobs/${jobId}/artifacts/file/reports/health-report.pdf`;
}

export async function sendGoogleChat(
  signals: CliSignals,
  scoring: ScoringResult,
  config: ScanConfig
): Promise<void> {
  const webhookUrl = config.notify?.googleChat?.webhookUrl;
  if (!webhookUrl) return;

  const gradeEmoji = scoring.grade === "A" ? "✅" : scoring.grade === "B" ? "🟢" : scoring.grade === "C" ? "🟡" : "🔴";

  const criticalItems: string[] = [];
  if (signals.has_secret_files.length > 0) criticalItems.push(`🔴 Secret files in repo (${signals.has_secret_files.length})`);
  if ((signals.content?.secret_hits.length ?? 0) > 0) criticalItems.push(`🔴 Hardcoded credentials (${signals.content?.secret_hits.length})`);
  if ((signals.deps?.vulnerable.length ?? 0) > 0) criticalItems.push(`⚠️ Vulnerable deps: ${signals.deps?.vulnerable.map((v) => v.name).slice(0, 2).join(", ")}`);
  if (signals.test_files === 0) criticalItems.push("⚠️ No tests");

  const scoreLines = Object.entries(scoring.scores)
    .map(([dim, ds]) => {
      const icon = ds.score >= 7.5 ? "🟢" : ds.score >= 5.5 ? "🟡" : "🔴";
      const label = dim.replace(/_/g, " ").replace(/\b\w/g, (l) => l.toUpperCase());
      return `${icon} <b>${label}:</b> ${ds.score.toFixed(1)}/10`;
    })
    .join("<br>");

  const criticalHtml = criticalItems.length > 0
    ? `<br><b>⚠️ Action Required:</b><br>${criticalItems.map((i) => `• ${i}`).join("<br>")}`
    : "";

  const artifactUrl = ciArtifactUrl();

  const widgets: object[] = [
    {
      textParagraph: {
        text: `${scoreLines}${criticalHtml}<br><i>Scanned ${new Date(signals.scanned_at).toLocaleString()}</i>`,
      },
    },
  ];

  const payload = {
    cards: [
      {
        header: {
          title: `${gradeEmoji} ${signals.project_name} Health Report`,
          subtitle: `Grade ${scoring.grade}  ·  ${scoring.health_score}/100  ·  ${scoring.verdict.replace("_", " ")}`,
          imageUrl: "https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/health_and_safety/default/48px.svg",
        },
        sections: [
          { widgets },
          ...(artifactUrl
            ? [{
                widgets: [{
                  buttons: [{
                    textButton: {
                      text: "📄 Download PDF Report",
                      onClick: { openLink: { url: artifactUrl } },
                    },
                  }],
                }],
              }]
            : []),
        ],
      },
    ],
  };

  try {
    const res = await fetch(webhookUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });
    if (!res.ok) {
      const body = await res.text().catch(() => "");
      process.stderr.write(`[scan] Google Chat webhook returned ${res.status}: ${body}\n`);
    } else {
      const note = artifactUrl ? " (with PDF download button)" : "";
      process.stdout.write(`[scan] Google Chat notification sent${note}\n`);
    }
  } catch (e) {
    process.stderr.write(`[scan] Google Chat send failed: ${(e as Error).message}\n`);
  }
}

// ── Combined notify ───────────────────────────────────────────────────────────

export async function notify(
  pdfBuffer: Buffer,
  signals: CliSignals,
  scoring: ScoringResult,
  recipients: string[],
  config: ScanConfig
): Promise<void> {
  await Promise.allSettled([
    sendEmail(pdfBuffer, signals, scoring, recipients, config),
    sendGoogleChat(signals, scoring, config),
  ]);
}
